CREATE TABLE IF NOT EXISTS cliente(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(255) NOT NULL,
    cpf VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    telefone VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL,

    -- Campos do Value Object (Endereco)
    rua VARCHAR(255),
    numero VARCHAR(255),
    cidade VARCHAR(255),
    estado VARCHAR(255),
    cep VARCHAR(255),

    cadastrado_em DATE, -- Boa prática: usar snake_case no banco


    CONSTRAINT pk_clientes PRIMARY KEY (id),
    CONSTRAINT uk_clientes_cpf UNIQUE (cpf),
    CONSTRAINT uk_clientes_email UNIQUE (email)
)